require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

inherit_from:
 - .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - '*.gemspec'
    - 'Gemfile'
    - vendor/bundle/ruby/**/*

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Rake/Desc:
  Exclude:
    - Rakefile

RSpec/VariableName:
  Exclude:
    - spec/lib/dispatch-rider/publisher/base_spec.rb

Style/StringLiterals:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/dispatch-rider.rb
    - spec/lib/dispatch-rider_spec.rb

Style/RedundantException:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    detect: find

# Github's PR width is 145 characters
Layout/LineLength:
  Max: 141
  AllowURI: true

# Align with the style guide, we don't prefer anything
#Style/CollectionMethods:
  #Enabled: false

Metrics/AbcSize:
  Description: A calculated magnitude based on number of assignments, branches, and
    conditions.
  Enabled: true
  Max: 22
