# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - 2.7
          - 2.6
        awssdk:
          - v1
          - v3
        gemfile:
          - Gemfile-5-2
          - Gemfile-6-0
          - Gemfile-6-1
          - Gemfile-7-0
        exclude:
        - gemfile: Gemfile-7-0
          ruby: 2.6
        - gemfile: Gemfile-5-2
          ruby: '3.0'

    env:
      AWS_SDK_VER: ${{ matrix.awssdk }}
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}
      AWS_REGION: us-east1
      CI: true
      COVERALLS_REPO_TOKEN: 7XadchWU3QuK3zHjHMRbFRr2wKxKckxPw
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Rubocop
      run: bundle exec rubocop -c .rubocop.yml
    - name: Rspec
      run: bundle exec rspec
